on:
    push:
        branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Setup node
              uses: actions/setup-node@v6
              with:
                  node-version: 25

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Setup gcloud
              uses: google-github-actions/setup-gcloud@v3
              with:
                  credentials_json: ${{ secrets.GCP_CREDENTIALS }}

            - name: Push it to Google Artifact Registry
              run: gcloud builds submit --tag asia-south1-docker.pkg.dev/romeosarkar10x-notely/notely-ar-repo/notely:latest .
